"""Blind OFDM geometry: survey has to be able to FIND fft_len/cp_len, not
just confirm a guess.

Nothing in survey measured multicarrier structure at all — the symbol_rate
block is single-carrier cyclostationary and reports eye_confirmed False on
OFDM, and ofdm_frame_sync_probe takes the whole geometry as input. So the one
thing an operator cannot guess had to be guessed.
"""

from __future__ import annotations

import numpy as np
import numpy.typing as npt

from marconi.survey.measure import _multicarrier

_FS = 2_048_000.0


def _ofdm(
    fft_len: int, cp_len: int, n_syms: int, seed: int = 3
) -> npt.NDArray[np.complex64]:
    """Textbook OFDM from the definition: random QPSK on every subcarrier, an
    IFFT per symbol, and the last cp_len samples of each useful part copied in
    front of it. Not generated by inverting the estimator under test."""
    rng = np.random.default_rng(seed)
    out: list[npt.NDArray[np.complex64]] = []
    for _ in range(n_syms):
        cells = rng.choice([1 + 1j, 1 - 1j, -1 + 1j, -1 - 1j], fft_len)
        useful = np.fft.ifft(cells).astype(np.complex64)
        out.append(np.concatenate([useful[fft_len - cp_len :], useful]))
    x = np.concatenate(out).astype(np.complex64)
    scale = float(np.sqrt(np.mean(np.abs(x) ** 2)))
    norm: npt.NDArray[np.complex64] = (x / scale).astype(np.complex64)
    return norm


def _noisy(x: npt.NDArray[np.complex64], snr_db: float) -> npt.NDArray[np.complex64]:
    rng = np.random.default_rng(17)
    n = 10 ** (-snr_db / 20) / np.sqrt(2)
    noise = n * (rng.standard_normal(x.size) + 1j * rng.standard_normal(x.size))
    out: npt.NDArray[np.complex64] = (x + noise).astype(np.complex64)
    return out


def test_geometry_is_recovered_from_the_cyclic_prefix_alone() -> None:
    mc = _multicarrier(_ofdm(1024, 128, 400), _FS)
    assert mc is not None
    assert mc.fft_len == 1024
    assert mc.subcarrier_spacing_hz == _FS / 1024
    # symbol_len is the broad estimate; a few samples is the honest claim
    assert abs(mc.symbol_len - 1152) <= 4
    assert abs(mc.cp_len - 128) <= 4
    # cp_len / symbol_len is what the correlation height means
    assert abs(mc.cp_correlation - 128 / 1152) < 0.05


def test_a_different_geometry_is_not_answered_with_the_first_one() -> None:
    """The mutation guard: change the transmitter, the answer has to move."""
    a = _multicarrier(_ofdm(256, 64, 900), _FS)
    b = _multicarrier(_ofdm(2048, 256, 200), _FS)
    assert a is not None and b is not None
    assert a.fft_len == 256 and b.fft_len == 2048
    assert abs(a.cp_len - 64) <= 4 and abs(b.cp_len - 256) <= 8


def test_geometry_survives_noise() -> None:
    mc = _multicarrier(_noisy(_ofdm(512, 64, 700), 6.0), _FS)
    assert mc is not None
    assert mc.fft_len == 512
    assert mc.peak_ratio > 3.0


def test_a_single_carrier_signal_reports_no_multicarrier_block() -> None:
    """The false-positive guard. A cyclic prefix is a specific structure; a
    QPSK burst train and band-limited noise must not mint one."""
    rng = np.random.default_rng(2)
    n = 1 << 18
    syms = rng.choice([1 + 1j, 1 - 1j, -1 + 1j, -1 - 1j], n // 8)
    psk = np.repeat(syms, 8).astype(np.complex64)
    assert _multicarrier(psk, _FS) is None

    noise = (rng.standard_normal(n) + 1j * rng.standard_normal(n)).astype(np.complex64)
    assert _multicarrier(noise, _FS) is None
