"""psk_soft_demap: the single-carrier entry to the soft coding lane.

The coding lane (deinterleave/depuncture/fec) requires ("f", SOFT); before this
stage the only producer was dqpsk_soft_demap, so no single-carrier modulation
could reach fec at all. The stimulus here is CCSDS rate-1/2 K=7 (polys 0o171,
0o133) -- the standard space-link convolutional code, generated by gnuradio's
own fsm encoder so encoder and decoder agree by construction.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from marconi.core.bitfile import harden, read_bits, read_llrs
from marconi.core.descriptor import Carrier, Descriptor
from marconi.core.levels import Level
from marconi.core.params import ParamValue
from marconi.phy.backends.gnuradio.runner import GnuRadioBackend, ensure_worker_warm
from marconi.phy.compiler import CompileError, compile_modem
from marconi.phy.models import ModemSpec, ModemStep
from marconi.phy.stages import stage_registry

SYM_C = Descriptor(Level.SYMBOLS, "c", carrier=Carrier.SOFT)
_POLYS = [0o171, 0o133]
_D = len(_POLYS)
_TAIL = 6
_FRAME_BITS = 512


def _run(path: list[ModemStep], sym: np.ndarray, tmp: Path, tag: str, ext: str) -> Path:
    src = tmp / f"in_{tag}.cf32"
    np.asarray(sym, np.complex64).tofile(src)
    snk = tmp / f"out_{tag}.{ext}"
    pipe = compile_modem(
        ModemSpec(symbol_rate=1.0, path=path),
        stage_registry(),
        direction="rx",
        sample_rate=1.0,
        start=SYM_C,
        source_io={"path": str(src)},
        sink_io={"path": str(snk)},
    )
    r = GnuRadioBackend().run_pipeline(pipe, timeout=180.0)
    assert r.status == "ok", r
    return snk


def _points(order: int) -> tuple[np.ndarray, int]:
    from gnuradio import digital

    con = {
        2: digital.constellation_bpsk,
        4: digital.constellation_qpsk,
        8: digital.constellation_8psk,
    }[order]()
    return np.asarray(con.points()), con.bits_per_symbol()


def _ccsds_encode(info: np.ndarray) -> np.ndarray:
    from gnuradio import blocks, gr, trellis

    padded = np.concatenate([info, np.zeros(_TAIL, np.uint8)]).astype(np.uint8)
    tb = gr.top_block()
    snk = blocks.vector_sink_b()
    tb.connect(
        blocks.vector_source_b(padded.tolist(), False),
        trellis.encoder_bb(trellis.fsm(1, _D, _POLYS), 0),
        snk,
    )
    tb.run()
    osyms = np.asarray(snk.data(), np.uint8)
    return np.stack([(osyms >> (_D - 1 - j)) & 1 for j in range(_D)], axis=1).reshape(
        -1
    )


def _fec_step() -> ModemStep:
    params: dict[str, ParamValue] = {
        "scheme": "cc",
        "rate_inv": _D,
        "polys": list(_POLYS),
        "frame_bits": _FRAME_BITS,
        "tail": _TAIL,
    }
    return ModemStep(conv="fec", params=params)


@pytest.mark.parametrize("order", [2, 4, 8])
def test_soft_demap_hardens_to_the_hard_demap(order: int, tmp_path: Path) -> None:
    """Two demaps of the same constellation must agree on the bits.

    This is the invariant that catches a sign or bit-order mismatch:
    constellation_soft_decoder emits log P(1)/P(0), the opposite sign from
    trellis_viterbi's metric table and from core.bitfile.harden.
    """
    ensure_worker_warm()
    pts, k = _points(order)
    idx = np.random.default_rng(order).integers(0, order, 2000)
    sym = pts[idx]
    hard = read_bits(
        _run(
            [ModemStep(conv="psk_demap", params={"order": order})],
            sym,
            tmp_path,
            f"h{order}",
            "u8",
        )
    )
    soft = harden(
        read_llrs(
            _run(
                [ModemStep(conv="psk_soft_demap", params={"order": order})],
                sym,
                tmp_path,
                f"s{order}",
                "f32",
            )
        )
    )
    assert soft.size == hard.size == idx.size * k
    assert np.array_equal(soft, hard)


def test_hard_demap_cannot_reach_the_coding_lane() -> None:
    """Why this stage exists: the coding lane is soft-only by contract."""
    for demap, expect_ok in (("psk_demap", False), ("psk_soft_demap", True)):
        path = [
            ModemStep(conv=demap, params={"order": 4}),
            ModemStep(conv="deinterleave", params={"perm": [0, 2, 1, 3]}),
        ]
        spec = ModemSpec(symbol_rate=1.0, path=path)
        if expect_ok:
            compile_modem(
                spec,
                stage_registry(),
                direction="rx",
                sample_rate=1.0,
                start=SYM_C,
                source_io={"path": "in.cf32"},
                sink_io={"path": "out.f32"},
            )
        else:
            with pytest.raises(CompileError, match="accepts item_type 'f'"):
                compile_modem(
                    spec,
                    stage_registry(),
                    direction="rx",
                    sample_rate=1.0,
                    start=SYM_C,
                    source_io={"path": "in.cf32"},
                    sink_io={"path": "out.f32"},
                )


def test_soft_lane_recovers_ccsds_coded_bits_exactly(tmp_path: Path) -> None:
    ensure_worker_warm()
    pts, _ = _points(4)
    info = np.random.default_rng(7).integers(0, 2, _FRAME_BITS).astype(np.uint8)
    coded = _ccsds_encode(info)
    assert coded.size == (_FRAME_BITS + _TAIL) * _D
    pairs = coded.reshape(-1, 2)
    sym = pts[pairs[:, 0] * 2 + pairs[:, 1]]
    out = read_bits(
        _run(
            [ModemStep(conv="psk_soft_demap", params={"order": 4}), _fec_step()],
            sym,
            tmp_path,
            "clean",
            "u8",
        )
    )
    assert out.size == _FRAME_BITS
    assert np.array_equal(out, info)


def test_soft_viterbi_corrects_errors_the_uncoded_link_makes(tmp_path: Path) -> None:
    """Coding gain through shipped vocabulary, with the uncoded arm as control.

    At Es/N0 4 dB the hard symbol decision on these exact symbols errs on ~5% of
    coded bits; the soft lane recovers the frame exactly. Measured over 5 seeds:
    uncoded 0.041-0.058, coded 0.0 every time.
    """
    ensure_worker_warm()
    pts, _ = _points(4)
    rng = np.random.default_rng(11)
    info = rng.integers(0, 2, _FRAME_BITS).astype(np.uint8)
    coded = _ccsds_encode(info)
    pairs = coded.reshape(-1, 2)
    clean = pts[pairs[:, 0] * 2 + pairs[:, 1]]

    es = float(np.mean(np.abs(clean) ** 2))
    noise = np.sqrt(es / (2 * 10 ** (4.0 / 10)))
    g = rng.standard_normal(clean.size) + 1j * rng.standard_normal(clean.size)
    noisy = clean + noise * g

    hi = np.argmin(np.abs(noisy[:, None] - pts[None, :]), axis=1)
    uncoded_ber = float(
        np.mean(np.stack([hi >> 1, hi & 1], axis=1).reshape(-1) != coded)
    )
    assert uncoded_ber > 0.02, f"control arm too clean to prove anything: {uncoded_ber}"

    out = read_bits(
        _run(
            [ModemStep(conv="psk_soft_demap", params={"order": 4}), _fec_step()],
            noisy,
            tmp_path,
            "noisy",
            "u8",
        )
    )
    assert out.size == _FRAME_BITS
    assert np.array_equal(out, info), (
        f"soft lane failed to correct: BER "
        f"{float(np.mean(out != info))} with uncoded {uncoded_ber}"
    )
